modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="parrying"
version="2.3"
displayName="Parrying"
authors="theishiopian"
description='''Improving Minecraft combat with new mechanics and weapons!'''