modLoader="javafml"
loaderVersion="[35,36,)"
license="All rights reserved"
[[mods]]
modId="parrying"
version="2.0.1"
displayName="Parrying"
authors="theishiopian"
description='''Improving Minecraft combat with new mechanics!'''
[[dependencies.parrying]]
modId = "patchouli"
mandatory = false
versionRange = "[1.16.4-53,)"
ordering = "BEFORE"
side = "BOTH"