modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="parrying"
version="2.4"
displayName="Parrying"
authors="theishiopian"
credits="ArcanePhysics, for testing help, y3z0n, for some of the foley sounds"
description='''Improving Minecraft combat with new mechanics and weapons!'''