modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="parrying"
version="1.3"
displayName="Parrying"
authors="theishiopian"
description='''
A mod about blocking hits
'''
